// Central site configuration. All copy, URLs and metadata live here, never
// hard-coded into components.

export const siteConfig = {
	name: 'Void Tales',
	titleTemplate: '%s · Void Tales',
	description: 'A station between worlds ✨',
	url: 'https://portal.voidtales.win',
	themeColor: '#0a0714',

	// Generated by .claude/skills/brand-assets/scripts/gen-og.mjs. Raster, not
	// SVG: Discord, X and Slack do not render SVG link previews.
	ogImage: '/images/og-image.webp',
	twitterImage: '/images/og-image.webp',
	twitterCard: 'summary_large_image',
	twitterSite: '@shinsnowly',

	// Minecraft server shown in the status panel. Queried client-side against
	// api.mcstatus.io (which sends `access-control-allow-origin: *`).
	mcServerHost: 'play.voidtales.win',
	mcServerPort: 25565,

	modrinthUrl: 'https://modrinth.com/modpack/void-tales',
	discordUrl: 'https://discord.voidtales.win',
	galleryUrl: 'https://gallery.voidtales.win',

	hero: {
		eyebrow: 'Minecraft modpack and server',
		title: 'Void Tales',
		// Rendered in the accent colour. Must be a substring of `title`.
		titleAccent: 'Tales',
		subtitle:
			'Six shattered realms, the fragments of a fallen goddess, and the Soul Station between them.',
		ctaLabel: 'Get the Modpack',
	},

	gallery: {
		title: 'Echoes from the Station',
		body: 'Glimpses across realms, caught between memory and motion. Each fragment is a path back to what was lost.',
		moreLabel: 'See all screenshots',
		moreHint: 'gallery.voidtales.win',
	},

	trailer: {
		title: 'Watch the Trailer',
		subtitle: 'Step into the world of Void Tales.',
		embedUrl: 'https://www.youtube-nocookie.com/embed/sIdqXmTkGsE',
	},

	join: {
		title: 'Three steps to the Station',
		// The step content is the label; no "Stage 1 / Step 2" prefixes.
		steps: [
			{
				title: 'Get the modpack from Modrinth',
				body: 'One download. Everything the server runs is inside it.',
			},
			{
				title: 'Install it in your launcher',
				body: 'The Modrinth App, Prism Launcher and ATLauncher all import the pack directly.',
			},
			{
				title: 'Connect to play.voidtales.win',
				body: 'Add the address, hit join, and the Station is open.',
			},
		],
	},

	social: {
		title: 'Follow the journey',
	},

	footer:
		'Void Tales ~ Created by Hyphonical & Inventory 💙 Not affiliated with Mojang or Microsoft. All rights reserved.',
};

// The two realm panels. Rendered as a sticky stack, mirrored between the two.
export const storySections = [
	{
		title: 'Through Ash and Arcana',
		image: '/images/portal-1.webp',
		imageAlt: 'A ruined keep wrapped in red autumn foliage under a burning sky.',
		body: 'You awaken in a world undone, where the goddess Phia lies scattered and silent, her fragments hidden across realms touched by the void. At the center of it all stands the Soul Station, a place where memory drifts, where paths between worlds converge. To walk this journey is to seek not only the pieces of a fallen divinity, but also the shape of your own forgotten self.',
		points: [
			'Gather Phia’s fragments, hidden in worlds fractured by the void.',
			'Shape your soul with relics, sigils, and attunements.',
			'Confront the trials that guard the way between memory and rebirth.',
		],
	},
	{
		title: 'The Shattered Realms',
		image: '/images/portal-2.webp',
		imageAlt: 'A stone colonnade hung with blossom and lanterns, lit by a low sun.',
		body: 'The lands you cross are more than ruins. They are kingdoms long surrendered to time. In the autumn-bound halls of Falwhind, beneath the endless trees of Ibya, or in the buried stone of Aridia, every shadow holds its own memory. Battles rise and fall, strange events twist the present, and creatures beyond reason linger in the dark. Here, to lose yourself is to step closer to the truth the world has hidden.',
		points: [
			'Wander realms each marked by their own history and peril.',
			'Face encounters, events, and challenges that shift with the world.',
			'Discover the strange beauty of being lost, and the wonder of finding your way.',
		],
	},
];

// The horizontal snap strip. grid-3.webp is deliberately absent: it is
// byte-identical to portal-2.webp, which already carries the second realm panel.
export const galleryImages = [
	{
		src: '/images/grid-1.webp',
		alt: 'Pale stone arches breaking apart in a violet sky, debris falling into cloud.',
	},
	{
		src: '/images/grid-2.webp',
		alt: 'A lantern-lit walkway spanning dark cliffs under a crescent moon.',
	},
	{
		src: '/images/grid-4.webp',
		alt: 'A vast dark hall lit by hundreds of lanterns and shafts of teal light.',
	},
	{
		src: '/images/grid-5.webp',
		alt: 'A moss-covered stone dome rising out of a bright green valley.',
	},
	{
		src: '/images/grid-6.webp',
		alt: 'Sunlight falling through a flowering stone canopy above a garden pool.',
	},
];
