// Central site configuration. All copy, URLs and metadata live here, never
// hard-coded into components.

export const siteConfig = {
	name: 'Void Tales',
	titleTemplate: '%s · Void Tales',
	description: 'Drawn To Light ✨',
	url: 'https://portal.voidtales.win',
	themeColor: '#0a0714',

	// Generated by .claude/skills/brand-assets/scripts/gen-og.mjs. Raster, not
	// SVG: Discord, X and Slack do not render SVG link previews.
	ogImage: '/images/og-image.webp',
	twitterImage: '/images/og-image.webp',
	twitterCard: 'summary_large_image',
	twitterSite: '@shinsnowly',

	// Minecraft server shown in the status panel. Queried client-side against
	// api.mcstatus.io (which sends `access-control-allow-origin: *`).
	mcServerHost: 'play.voidtales.win',
	mcServerPort: 25565,

	modrinthUrl: 'https://modrinth.com/modpack/void-tales',
	discordUrl: 'https://discord.gg/QEMQsFect6',
	galleryUrl: 'https://gallery.voidtales.win',

	hero: {
		eyebrow: 'Minecraft modpack and server',
		title: 'Void Tales',
		// Rendered in the accent colour. Must be a substring of `title`.
		titleAccent: 'Tales',
		subtitle: 'Mend a broken world, and uncover the truth within yourself.',
		ctaLabel: 'Get the Modpack',
	},

	gallery: {
		title: 'Community Screenshots',
		body: 'Take a look at the world of Void Tales, its regions, bosses, and handcrafted environments.',
		moreLabel: 'See all screenshots',
		moreHint: 'gallery.voidtales.win',
	},

	trailer: {
		title: 'Watch the Trailer',
		subtitle: 'Step into the world of Void Tales.',
		embedUrl: 'https://www.youtube-nocookie.com/embed/sIdqXmTkGsE?si=WFjpRQjjKl9FE9li',
	},

	join: {
		title: 'Start Your Journey',
		// The step content is the label; no "Stage 1 / Step 2" prefixes.
		steps: [
			{
				title: 'Get the modpack from Modrinth',
				body: 'Install the official Void Tales modpack from Modrinth.',
			},
			{
				title: 'Install it in your launcher',
				body: 'The Modrinth App, Prism Launcher and ATLauncher all import the pack directly.',
			},
			{
				title: 'Launch & Play',
				body: 'Start Void Tales and join the server.',
			},
		],
	},

	social: {
		title: 'Follow the journey',
	},

	footer:
		'Void Tales ~ Created by Hyphonical & Inventory 💙 Not affiliated with Mojang or Microsoft. All rights reserved.',
};

// The two realm panels. Rendered as a sticky stack, mirrored between the two.
export const storySections = [
	{
		title: 'Remember Why You Fell in Love with Games',
		image: '/images/portal-1.webp',
		imageAlt: 'A ruined keep wrapped in red autumn foliage under a burning sky.',
		body: 'Void Tales is inspired by the adventures that made us fall in love with games in the first place. A world that rewards curiosity and lets unforgettable moments happen naturally instead of pointing you toward them.',
		points: [
			'Explore without being led every step of the way.',
			'Discover hidden places, secrets, and memorable encounters.',
			'Experience a handcrafted world built to be explored, not rushed.',
		],
	},
	{
		title: 'A World Made by Hand',
		image: '/images/portal-2.webp',
		imageAlt: 'A stone colonnade hung with blossom and lanterns, lit by a low sun.',
		body: 'Void Tales was built with the belief that worlds should feel discovered, not generated. Every region, creature, and encounter has been crafted with its own identity, history, and purpose.',
		points: [
			'Explore places shaped by years of passion and dedication.',
			'Meet characters and creatures with stories of their own.',
			'Find moments that were created to be remembered.',
		],
	},
];

// The horizontal snap strip. grid-3.webp is deliberately absent: it is
// byte-identical to portal-2.webp, which already carries the second realm panel.
export const galleryImages = [
	{
		src: '/images/grid-1.webp',
		alt: 'Pale stone arches breaking apart in a violet sky, debris falling into cloud.',
	},
	{
		src: '/images/grid-2.webp',
		alt: 'A lantern-lit walkway spanning dark cliffs under a crescent moon.',
	},
	{
		src: '/images/grid-4.webp',
		alt: 'A vast dark hall lit by hundreds of lanterns and shafts of teal light.',
	},
	{
		src: '/images/grid-5.webp',
		alt: 'A moss-covered stone dome rising out of a bright green valley.',
	},
	{
		src: '/images/grid-6.webp',
		alt: 'Sunlight falling through a flowering stone canopy above a garden pool.',
	},
];
